### PR TITLE
Add CAG: Change

### PR DESCRIPTION
**Pull request by mustafatufan**
- [x] I understand that token listing is not required to use the Uniswap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [x] I will not ping the Discord about this listing request.

Token Address: [0x7d4b8cce0591c9044a22ee543533b72e976e36c3](https://etherscan.io/token/0x7d4b8cce0591c9044a22ee543533b72e976e36c3)
Token Name (from contract): Change COIN
Token Decimals (from contract): 18
Token Symbol (from contract): CAG
Uniswap V2 Pair Address of Token: [0xedd0e4f572f33a6fc2f3b80999b533ed177693be](https://uniswap.info/pair/0xedd0e4f572f33a6fc2f3b80999b533ed177693be)

Link to the official homepage of token: https://www.changeinvest.com/investor
Link to CoinMarketCap or CoinGecko page of token: https://coinmarketcap.com/currencies/change

### CODE REVIEW

**Comment by mustafatufan** [comment]
Hi @callil,

Could you help about this PR?

**Comment by callil** [comment]
I've re-opened the PR and will close this. We can continue the conversation there :)

**Comment by mustafatufan** [comment]
Hey @callil,

I didn't get why did you close this one.

This PR is adding to Uniswap's default list which we want to be in as well.

The one that you reopened is Change's its own list: https://github.com/Uniswap/tokenlists-org/pull/357

I would like to see both as merged if it is possible. :)

Thank you.

**Comment by callil** [comment]
This is not the place to request to be on the default list. This repository is only for adding other lists to the tokenlist website

**Pull request closed without merging**
